### ISSUE TITLE
Getting the below error message when uploading "alexaMagicMirrorApp" as lambda function

### ISSUE THREAD

**Issue by vikashag** [mexitek/alexaMagicMirrorApp#1]
Hi Arlo,

Getting the below error message while testing the lambda function.

{
  "errorMessage": "Cannot find module '/var/task/index'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:417:25)",
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)"
  ]
}

Along with that if I am trying to open the code in "in-line Editing" option then getting this error.

Error opening file
Could not open file: /index.js
The file could not be found on the file system.

Can you please help me on this.

Thanks,
Vikash

**Comment by mexitek** [comment]
I believe you are not Zipping the contents correctly. Make sure you zip the contents of the project directly. DO NOT zip the folder containing the contents. 

To make sure you are doing it correctly:
* Open your zip
* you should see index.js right away
  * If you see a folder first, then inside you have index.js, you are doing it wrong.

**Comment by vikashag** [comment]
Thank you Arlo. It's working for me now.

**Comment by mexitek** [comment]
No worries. I was also stuck on this for a few hours my first time.
